on:
  push:
    branches: [ "Dev" ]

name: Build docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker compose up -d
          docker compose exec php composer install
          docker compose exec php php bin/console doctrine:database:create
          docker compose exec php php bin/console doctrine:migrations:migrate
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: login to github container regestry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to github registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/maxime-louis14/inventaire18_nws-php:latest
          target: inventaire 

